{"name": "test_login_0_error[data0]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '13423456789', 'pwd': '123', 'expected': '此账号没有经过授权，请联系管理员!'}"}], "start": 1569945389190, "stop": 1569945390088, "uuid": "8412160f-42dd-480e-bb65-5f14c4bb7add", "historyId": "33ebfa5abb8980fb13fb895f9d879d26", "testCaseId": "4b76fc265503f1878bd277c307b89de6", "fullName": "test_cases.test_login.TestLogin#test_login_0_error", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-I3J3MGM"}, {"name": "thread", "value": "528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login"}]}